model:
  path: "HuggingFaceTB/SmolLM2-135M-Instruct"

fsdp: False

batch_size: 64

quantization: False

enable_fsdp: False

lr: 0.000002

weight_decay: False

dataset_path: "/data/nvme7n1p1/critical_all/critical_instruct/2024.09.06_instruct_kk_benchmarks-arc_119687.json"

max_length: 2048