model:
  # path: "HuggingFaceTB/SmolLM2-135M-Instruct"
  # path: "/data/nvme7n1p1/mistral_models/models--mistralai--Mixtral-8x7B-Instruct-v0.1/snapshots/Mixtral-8x7B-Instruct-v0.1"
  # path: "/raid/vladimir_albrekht/huggingface/models--meta-llama--Meta-Llama-3.1-8B-Instruct/snapshots/5206a32e0bd3067aef1ce90f5528ade7d866253f"
  path: "/raid/adal_abilbekov/workspace/own_fsdp/models/smollm2_135M"
  save_path: "/raid/adal_abilbekov/workspace/own_fsdp/models"

log:
  enable_wandb: True
  project_name: "my_train"

fsdp: True

batch_size: 24

quantization: False

enable_fsdp: True

adam_beta1: 0.9

adam_beta2: 0.95

adam_eps: 1.0e-08

lr: 3.0e-05

min_lr: 1.0e-06

weight_decay: 0.01

dataset_path: "/raid/adal_abilbekov/workspace/own_fsdp/datasets/2024.09.06_instruct_kk_benchmarks-gsm8k_628249.json"

max_length: 2048

save_step: 1000

save_path: "/home/adal/workspace/models/training_try1"

dataset_type: "json"

mixed_precision: True

use_peft: True

fsdp_cpu_offload: False

low_cpu_fsdp: False

brain_float: True