model:
  path: "HuggingFaceTB/SmolLM2-135M-Instruct"

fsdp: False

batch_size: 64

quantization: False

enable_fsdp: False

lr: 0.000002

weight_decay: False

dataset_path: "datset.parquet"

max_length: 512

save_step: 50

save_path: "/home/adal/workspace/models/training_try1"

dataset_type: parquet